services:
  suitecrm:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: suitecrm
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=suitecrm
      - DATABASE_USER=suitecrm
      - DATABASE_PASSWORD=suitecrm_password
      - SITE_URL=http://localhost:8080
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./SuiteCRM:/var/www/html
      - suitecrm_uploads:/var/www/html/upload
      - suitecrm_cache:/var/www/html/cache
    depends_on:
      - db
    networks:
      - suitecrm-network

  db:
    image: mysql:8.0
    container_name: suitecrm_db
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=suitecrm
      - MYSQL_USER=suitecrm
      - MYSQL_PASSWORD=suitecrm_password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - suitecrm-network

  phpmyadmin:
    profiles:
      - dev
    image: phpmyadmin/phpmyadmin
    container_name: suitecrm_phpmyadmin
    platform: linux/amd64
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - suitecrm-network

volumes:
  db_data:
  suitecrm_uploads:
  suitecrm_cache:

networks:
  suitecrm-network:
    driver: bridge