{*
 * Financial Dashboard Template
 * Display financial metrics and valuation calculations
 *}

<div id="financial-dashboard" class="financial-dashboard-container">
    
    {* Header Section *}
    <div class="dashboard-header">
        <h2>Financial & Valuation Dashboard</h2>
        <div class="dashboard-subtitle">
            <span class="deal-name">{$DEAL_NAME}</span>
            <span class="deal-id">ID: {$DEAL_ID}</span>
        </div>
        <div class="dashboard-actions">
            <button id="refresh-dashboard" class="btn btn-primary">
                <i class="glyphicon glyphicon-refresh"></i> Refresh
            </button>
            <button id="export-dashboard" class="btn btn-default">
                <i class="glyphicon glyphicon-download"></i> Export
            </button>
            <button id="what-if-calculator" class="btn btn-success">
                <i class="glyphicon glyphicon-calculator"></i> What-If Analysis
            </button>
        </div>
    </div>

    {* Main Dashboard Grid *}
    <div class="dashboard-grid">
        
        {* Key Metrics Section *}
        <div class="dashboard-section key-metrics">
            <h3>Key Financial Metrics</h3>
            <div class="metrics-grid" id="key-metrics-container">
                {* Metrics will be populated by JavaScript *}
                <div class="metric-widget" id="asking-price-widget">
                    <div class="metric-label">Asking Price</div>
                    <div class="metric-value">-</div>
                </div>
                <div class="metric-widget" id="ttm-revenue-widget">
                    <div class="metric-label">TTM Revenue</div>
                    <div class="metric-value">-</div>
                </div>
                <div class="metric-widget" id="ttm-ebitda-widget">
                    <div class="metric-label">TTM EBITDA</div>
                    <div class="metric-value">-</div>
                </div>
                <div class="metric-widget" id="sde-widget">
                    <div class="metric-label">SDE</div>
                    <div class="metric-value">-</div>
                </div>
                <div class="metric-widget" id="ebitda-margin-widget">
                    <div class="metric-label">EBITDA Margin</div>
                    <div class="metric-value">-</div>
                </div>
                <div class="metric-widget" id="proposed-valuation-widget">
                    <div class="metric-label">Proposed Valuation</div>
                    <div class="metric-value">-</div>
                </div>
            </div>
        </div>

        {* Capital Stack Section *}
        <div class="dashboard-section capital-stack">
            <h3>Capital Stack</h3>
            <div class="capital-stack-container" id="capital-stack-container">
                <div class="stack-visual" id="capital-stack-visual">
                    {* Visual representation will be generated by JavaScript *}
                </div>
                <div class="stack-details">
                    <div class="stack-item equity">
                        <span class="stack-label">Equity</span>
                        <span class="stack-amount" id="equity-amount">-</span>
                        <span class="stack-percentage" id="equity-percentage">-</span>
                    </div>
                    <div class="stack-item senior-debt">
                        <span class="stack-label">Senior Debt</span>
                        <span class="stack-amount" id="senior-debt-amount">-</span>
                        <span class="stack-percentage" id="senior-debt-percentage">-</span>
                    </div>
                    <div class="stack-item seller-note">
                        <span class="stack-label">Seller Note</span>
                        <span class="stack-amount" id="seller-note-amount">-</span>
                        <span class="stack-percentage" id="seller-note-percentage">-</span>
                    </div>
                    <div class="stack-total">
                        <span class="stack-label">Total Deal Value</span>
                        <span class="stack-amount" id="total-deal-value">-</span>
                    </div>
                </div>
            </div>
        </div>

        {* Debt Coverage Analysis *}
        <div class="dashboard-section debt-coverage">
            <h3>Debt Coverage Analysis</h3>
            <div class="debt-coverage-container">
                <div class="coverage-metric">
                    <div class="metric-label">DSCR</div>
                    <div class="metric-value" id="dscr-value">-</div>
                    <div class="metric-status" id="dscr-status"></div>
                </div>
                <div class="coverage-details">
                    <div class="coverage-item">
                        <span class="label">Cash Flow Available</span>
                        <span class="value" id="cash-flow-available">-</span>
                    </div>
                    <div class="coverage-item">
                        <span class="label">Total Debt Service</span>
                        <span class="value" id="total-debt-service">-</span>
                    </div>
                    <div class="coverage-item">
                        <span class="label">Coverage Cushion</span>
                        <span class="value" id="coverage-cushion">-</span>
                    </div>
                </div>
            </div>
        </div>

        {* Comparables Section *}
        <div class="dashboard-section comparables">
            <h3>Market Comparables</h3>
            <div class="comparables-container">
                <div class="comparables-summary">
                    <div class="summary-metric">
                        <span class="label">Median Multiple</span>
                        <span class="value" id="median-multiple">-</span>
                    </div>
                    <div class="summary-metric">
                        <span class="label">Comparable Deals</span>
                        <span class="value" id="comparable-count">-</span>
                    </div>
                </div>
                <div class="comparables-list" id="comparables-list">
                    {* List will be populated by JavaScript *}
                </div>
            </div>
        </div>

        {* Valuation Analysis *}
        <div class="dashboard-section valuation-analysis">
            <h3>Valuation Analysis</h3>
            <div class="valuation-container">
                <div class="valuation-metric">
                    <span class="label">Implied Multiple</span>
                    <span class="value" id="implied-multiple">-</span>
                </div>
                <div class="valuation-metric">
                    <span class="label">Industry Multiple</span>
                    <span class="value" id="industry-multiple">-</span>
                </div>
                <div class="valuation-metric">
                    <span class="label">Target Multiple</span>
                    <span class="value" id="target-multiple">-</span>
                </div>
                <div class="valuation-chart" id="valuation-chart">
                    {* Chart will be rendered by JavaScript *}
                </div>
            </div>
        </div>

        {* ROI Metrics *}
        <div class="dashboard-section roi-metrics">
            <h3>Return Metrics</h3>
            <div class="roi-container">
                <div class="roi-metric">
                    <span class="label">Cash-on-Cash Return</span>
                    <span class="value" id="cash-on-cash">-</span>
                </div>
                <div class="roi-metric">
                    <span class="label">Break-Even Multiple</span>
                    <span class="value" id="break-even-multiple">-</span>
                </div>
                <div class="roi-metric">
                    <span class="label">Working Capital Req.</span>
                    <span class="value" id="working-capital">-</span>
                </div>
            </div>
        </div>

    </div>

    {* What-If Calculator Modal *}
    <div id="what-if-modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">What-If Analysis Calculator</h4>
                </div>
                <div class="modal-body">
                    <div class="what-if-container">
                        <div class="what-if-inputs">
                            <h5>Adjust Parameters</h5>
                            <div class="input-group">
                                <label>Purchase Price</label>
                                <input type="number" id="what-if-price" class="form-control">
                            </div>
                            <div class="input-group">
                                <label>Target Multiple</label>
                                <input type="number" id="what-if-multiple" class="form-control" step="0.1">
                            </div>
                            <div class="input-group">
                                <label>Revenue Growth %</label>
                                <input type="number" id="what-if-growth" class="form-control" step="0.1">
                            </div>
                            <div class="input-group">
                                <label>Equity %</label>
                                <input type="range" id="what-if-equity" min="0" max="100" value="30">
                                <span id="equity-percent-display">30%</span>
                            </div>
                        </div>
                        <div class="what-if-results">
                            <h5>Projected Results</h5>
                            <div id="what-if-results-container">
                                {* Results will be populated by JavaScript *}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="save-scenario">Save Scenario</button>
                </div>
            </div>
        </div>
    </div>

</div>

{* Initialize dashboard data *}
<script type="text/javascript">
    var financialData = {$FINANCIAL_DATA};
    var comparablesData = {$COMPARABLES_DATA};
    var capitalStackData = {$CAPITAL_STACK_DATA};
</script>